//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PantrTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_QuantityType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_QuantityType()
        {
            this.tbl_PostQuantity = new HashSet<tbl_PostQuantity>();
        }
    
        public int PK_QuantityType { get; set; }
        public string QuantityType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PostQuantity> tbl_PostQuantity { get; set; }
    }
}
