//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PantrTest.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Report
    {
        public int PK_Report { get; set; }
        public Nullable<int> FK_Reporter { get; set; }
        public Nullable<int> FK_Reported { get; set; }
        public string Report { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_User tbl_User1 { get; set; }
    }
}
