//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PantrTest.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Post()
        {
            this.tbl_Transaction = new HashSet<tbl_Transaction>();
        }
    
        public int PK_Post { get; set; }
        public Nullable<int> FK_Giver { get; set; }
        public Nullable<int> FK_Material { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<int> EndTime { get; set; }
        public Nullable<bool> Claimed { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Quantity { get; set; }
    
        public virtual tbl_Material tbl_Material { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Transaction> tbl_Transaction { get; set; }
    }
}
