//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PantrTest.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Transaction
    {
        public int PK_Transaction { get; set; }
        public Nullable<int> FK_Post { get; set; }
        public Nullable<int> FK_Panter { get; set; }
        public Nullable<bool> Collected { get; set; }
        public Nullable<bool> Annulled { get; set; }
    
        public virtual tbl_Post tbl_Post { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
