//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PantrTest.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PostQuantity
    {
        public int PK_PostQuantity { get; set; }
        public Nullable<int> FK_QuantityType { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> FK_Post { get; set; }
    
        public virtual tbl_Post tbl_Post { get; set; }
        public virtual tbl_QuantityType tbl_QuantityType { get; set; }
    }
}
